name: Release everything

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Bump, rebuild and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install -w

      # Produces 'applied' output. It indicates if the rest of the workflow
      # should run.
      - name: Bump versions
        id: version
        env:
          LOGFILE: tmp-log.txt
        run: |
          pnpm exec changeset version 2>&1 | tee $LOGFILE

          NO_CHANGESETS=$(grep -q "No unreleased changesets found, exiting" $LOGFILE && echo "0" || echo "1")
          APPLIED=$(grep -q "All files have been updated" $LOGFILE && echo "0" || echo "1")

          rm $LOGFILE

          if [[ "$NO_CHANGESETS" == "0" ]]; then
            echo "::set-output name=applied::false"
          elif [[ "$APPLIED" == "0" ]]; then
            echo "::set-output name=applied::true"
          else
            echo "Command `changeset version` printed unexpected output"
            exit 1
          fi

      - name: Rebuild packages
        if: steps.version.outputs.applied == 'true'
        run: |
          pnpm install
          pnpm run -r build
          pnpm install

      - name: Show changed files
        if: steps.version.outputs.applied == 'true'
        run: |
          git status

      - name: Commit file changes
        if: steps.version.outputs.applied == 'true'
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: release packages [skip ci]"
          push: false

      - name: Show committed files
        if: steps.version.outputs.applied == 'true'
        run: |
          git show

      - name: Publish with changesets
        if: steps.version.outputs.applied == 'true'
        id: changesets
        uses: changesets/action@v1.3.0
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes and tags
        if: steps.version.outputs.applied == 'true'
        run: git push --follow-tags
